// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3w-LFcQgnKqr5kwVFd69T19t-nAgtrVQ',
    appId: '1:158498278564:web:8caaa2f9cccd041d60ea31',
    messagingSenderId: '158498278564',
    projectId: 'chat-app-6d245',
    authDomain: 'chat-app-6d245.firebaseapp.com',
    storageBucket: 'chat-app-6d245.appspot.com',
    measurementId: 'G-Z4S3ZMVJY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD20nDkWCgHgdHNY_rdaHL5HSdJF5bfXKs',
    appId: '1:158498278564:android:f637950e7e8e2e8b60ea31',
    messagingSenderId: '158498278564',
    projectId: 'chat-app-6d245',
    storageBucket: 'chat-app-6d245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklBGYlctdHIteg2LC41AcpmzZBj5MsSw',
    appId: '1:158498278564:ios:6a9fc8da3ce8992360ea31',
    messagingSenderId: '158498278564',
    projectId: 'chat-app-6d245',
    storageBucket: 'chat-app-6d245.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3w-LFcQgnKqr5kwVFd69T19t-nAgtrVQ',
    appId: '1:158498278564:web:fb3a4e18d8719da560ea31',
    messagingSenderId: '158498278564',
    projectId: 'chat-app-6d245',
    authDomain: 'chat-app-6d245.firebaseapp.com',
    storageBucket: 'chat-app-6d245.appspot.com',
    measurementId: 'G-EYD549LE75',
  );
}
